---
- hosts: localhost
  connection: local
  become: yes

  tasks:
  - name: refresh package cache and update all packages (openSUSE Leap/Tumbleweed and SUSE)
    community.general.zypper:
      update_cache: yes
      name: "*"
      state: dist-upgrade
    when: ansible_distribution in ["openSUSE Tumbleweed", "SUSE", "openSUSE Leap"]   
  
  - name: refresh package cache and update all packages (RedHat and CentOS)
    dnf:
      name: "*"
      update_cache: yes
      state: latest
    when: ansible_distribution in ["CentOS", "RedHat", "Fedora"]

  - name: refresh package cache and update all packages (Ubuntu and Debian)
    apt:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install EPLE for CentOS
    package:
      name: epel-release
    when: ansible_distribution == "CentOS"

  - name: install packages
      package:
        name:
          - htop
          - tmux
          - neovim

  - name: copy custom .bashrcfile
    copy:
      src: files/bashrc
      dest: /home/freppa/.bashrc
      owner: freppa
      group: freppa


